### ISSUE TITLE
baseService 实现 account 注册登陆功能

### ISSUE THREAD

**Issue by TremblingV5** [cloudzenith/DouTok#6]
## What

提供全局唯一账号的能力

唯一账号绑定一个邮箱和一个手机号

1. 邮箱和手机号至少要提供一个
2. 密码加盐处理

**Comment by BaiZe1998** [comment]
0.1.0 使用 jwt 如何？

**Comment by TremblingV5** [comment]
> 0.1.0 使用 jwt 如何？

好，这个好说

**Comment by BaiZe1998** [comment]
baseService 这边只做 account 的管理，注册业务逻辑放到 core，包括 jwt
