### ISSUE TITLE
baseService 提供邮件能力和sms能力

### ISSUE THREAD

**Issue by TremblingV5** [cloudzenith/DouTok#7]
### 基础

 1. 给定邮箱、手机号，以及要发送的标题、内容等，可以发送邮件和短信。对于邮件，至少应能够发送纯文本的信息
 2. 通过配置项，开启mock模式，mock模式下不真的向运营商发送相关请求

### 扩展

1. 对邮件、短信的模板功能
3. 对邮件、短信的黑白名单功能

**Comment by BaiZe1998** [comment]
v0.1.0先不做这个吧

**Comment by TremblingV5** [comment]
> v0.1.0先不做这个吧

这个可以先留个壳子，依次有以下完成度：

1. 只保留查验验证码接口，无论传来的验证码是什么，都通过验证
2. 通过配置项开启mock模式，模拟验证码发送，可以模拟的位置包括日志、控制台等
3. 真实的向手机号、邮箱发送验证码

如果来不及，可以只完成第1级别的完成度，方便后续扩展即可
